### ISSUE TITLE
css

### ISSUE THREAD

**Issue by VenenoFSD** [VenenoFSD/travel-app#2]
```js
/** html5 语义化标签
 * title 、nav 、main 、article 、section 、aside（侧边栏）、header 、footer 、cite（引用）、pre（预格式化）、ins（插入）、insert（删除）
 */

/** Doctype
 * 不是 HTML 标签
 * html5：<!DOCTYPE html>
 * 两种模式：
 *    1. 严格模式：排版和 JS 运作模式是以该浏览器支持的最高标准运行
 *    2. 混杂模式，向后兼容，模拟老式浏览器，防止浏览器无法兼容页面
 */

/** 盒模型
 * 标准盒模型：width = content ，总宽度 = width + padding + border。对应 box-sizing：content-box
 * IE 盒模型：width = content + padding + border ，总宽度 = width。对应 box-sizing：border-box
 */

/** 0.5px 的线
 * transform: scaleY(0.5)
 */

/** link 与 @import
 * link 随页面加载而同时加载，@import 引用的 css 会在页面加载完后再加载
 */

/** BFC
 * 1. 概念：https://www.veneno.ink/bfc%e6%b7%b1%e5%85%a5%e7%90%86%e8%a7%a3/
 * 2. 应用场景：
 *    2.1 清除浮动
 *    2.2 自适应两栏布局
 * 3. BFC 部分成立条件：
 *    3.1 根元素
 *    3.2 float 不为 none
 *    3.3 position 为 fixed 或 absolute
 *    3.4 display 为 inline-x 或 table-x
 *    3.5 overflow 不为 visible 的块元素
 *    3.6 display 为 flex 、grid 的元素的直接子元素
 * 4. BFC 特性
 *    4.1 BFC 内的盒子垂直方向放置，margin 会重叠
 *    4.2 清除浮动（子元素为浮动元素）
 *    4.3 BFC 与浮动元素相邻时不会重叠，可利用此特性做自适应两栏布局
 */

/** 水平居中
 * 1. 行内元素：父元素 text-align: center
 * 2. 块级元素：margin: 0 auto
 * 3. 父元素： flex ，justify-content: center
 * 4. 子绝父相，子 left:50% ，translateX(-50%)
*/

// display:none ：不占据空间，修改属性会回流
// visibility:hidden ：元素隐藏，依然占据空间，修改会引起重绘，不会触发绑定事件，transition 无效
// opacity:0 ：元素隐藏，依然占据空间，修改会引起重绘，会触发绑定事件，transition 有效

/** 行内元素
 * 1. 非替换元素：margin ，padding 均为上下无效，左右有效
 * 2. 替换元素（img ，textarea ，input）：margin ，padding 有效，可设置宽高
 */

/** zoom 与 transform: scale()
 * 1. zoom 缩放改变占据空间的大小，因此改变会引起回流
 * 2. scale 缩放不会改变占据空间的大小，因此改变会引起重绘
 */

/** 清除浮动
 * 1. clear: left; 表示不允许左边有浮动的元素
 * 2. 父元素:after 或者手动添加块级子元素在末尾 ，然后设置 clear: both
 * 3. 父元素 -> BFC ，overflow: hidden
 */

// table 标签与样式对应
// table    { display: table }
// tr       { display: table-row }
// thead    { display: table-header-group }
// tbody    { display: table-row-group }
// tfoot    { display: table-footer-group }
// col      { display: table-column }
// colgroup { display: table-column-group }
// td, th   { display: table-cell }
// caption  { display: table-caption }

// rem：1rem = html 默认 font-size = 16px，为了计算方便，设置 html { font-size: 62.5% }，1rem = 10px

// 网页的宽度自动适应手机屏幕的宽度：<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no;">

/** 媒体查询
 * @media screen and|not|only (媒体功能: value) { ... }
 * 媒体功能：max-height，max-width，min-width，min-height
 * link 标签媒体查询：<link rel="stylesheet" href="a.css" media="screen and (min-width: 800px)">
 */

/** css3 硬件加速
 * 浏览器的 GPU 加速功能是将需要进行动画的元素提升到一个独立的层（layer），这样就可以避免浏览器进行重新布局（Reflow）和绘制（Repaint），将原先的浏览器使用 CPU 绘制位图来实现的动画效果转为让 GPU 使用图层合成（composite）来实现，如果两张图层内部没有发生改变，浏览器就不再进行布局和绘制，直接使用 GPU 的缓存来绘制每个图层，GPU 只负责将各个图层合成来实现动画，这就可以充分利用 GPU 的资源和优势，减轻 CPU 的负载，可以使动画更流畅
 * 使用 3D 硬件加速提升动画性能时，最好给元素增加一个 z-index 属性，人为干扰复合层的排序，可以有效减少 chrome 创建不必要的复合层，提升渲染性能，特别是移动端
 */

/** css 选择器
 * 1. +：例如 div + p 表示紧跟在 div 后面的 p 标签
 * 2. ~：如 p ~ ul 表示选择与 p 同级并且在 p 标签后面的所有 ul
 * 3. [attribute]：选择所有带 attribute 属性的标签
 * 4. [attribute=value]：...
 * 5. [attribute~=value]：选择属性有 value 的，例如 [title~=a] 匹配 <img title="a b">，<img title="a c">;
 * 6. [attribute|=value]：选择属性以 value- 开头的，例如 [lang|=en] 匹配 <p lang="en-a"></p>,<p lang="en-b"></p>;
 * 7. [attribute^=value]：选择属性以 value 开头的，例如 [lang^=en] 匹配 <p lang="en-a"></p>,<p lang="enb"></p>;
 * 8. [attribute$=value]：选择属性以 value 结尾的
 * 9. [attribute*=value]：选择属性包含 value 的
 * 10. :link（未访问状态）,:visited（已访问状态）,:hover,:active（按下状态）
 * 11. :first-letter：选择首个字母
 * 12. :first-line：选择第一行
 * 13. :first-child：例如 p:first-child，选择 p 标签，这个标签必须是其父元素的第一个子元素
 * 14. :last-child
 * 15. :before,:after
 * 16. :first-of-type：例如 p:first-type，选择父元素的第一个 p 标签
 * 17. :last-of-type
 * 18. :nth-child(n)：例如 p:nth-child(2)，选择 p 标签，这个标签必须是其父元素的第二个子元素
 * 19. :nth-last-child(n)：同上，区别在于倒数
 * 20. :nth-of-type(n)：例如 p:nth-of-type(2)，选择父元素的第二个 p 标签
 * 21. :nth-last-of-type(n)：同上，区别在于倒数
 * 22. :target：选择活动的 HTML 锚点
 * 23. ::selection：选中的文本
 */

// outline 与 border 区别：outline 不占据空间，针对表单元素等，在 focus 的时候显示，在 blur 的时候隐藏

// input 和 textarea 区别：input 需指定 type，单行；textarea 是封闭标签，多行

/** 点击穿透现象
 * 移动端 touch 执行大概 300ms 后 click 才被触发，会导致比如 touch 后蒙层消失，然后 300ms 后蒙层下元素 click 被触发等问题
 * 原因：touch 触发后，移动端需要 300ms 判断是否为双击放大，如果不是放大，就会触发 click
 * 解决：
 *    1. 不要混用 touch 和 click
 *    2. 推荐全部用 touch
 * 补充：PC端点击：mousedown -> mouseup（先于 click 触发） -> click；移动端：touchstart -> touchmove -> touchend
 */

/** 固定宽高比
 * 1. 使用 padding-bottom/top: xx% 。基于父元素 width 计算
 * 2. 视口单位 vw ，vh
 */

/** 解决 margin 坍塌（以 margin-top 为例）
 * 1. 父元素 padding-top
 * 2. 父元素 border
 * 3. 父元素 overflow: hidden
 * 4. 父元素 position: fixed
 * 5. 父元素 display: table
 * 6. 子元素前加一个兄弟 overflow: hidden
 */

// 用一个 div 模拟 textarea 的实现：设置属性 contenteditable="true"

// inline-block 元素之间的空隙使用 font-size: 0 来解决

/** rgba 与 opacity
 * 1. opacity 会继承父元素的 opacity 属性
 * 2. rgba 设置的元素的后代元素不会继承不透明属性
 */

// 浏览器支持小于 12px 的文字：transform: scale

/** background-clip：设置元素的背景（背景图片或颜色）延伸到指定区域下面
 * 1. border-box
 * 2. padding-box
 * 3. content-box
 * 4. text
 */

// 设置元素浮动后，元素 display 为 block

/** 换行
 * 1. word-break：单词应怎样断行
 *    1.1 keep-all：所有单词均不换行，只有空格能触发换行
 *    1.2 break-all：所有单词若超出边界均要换行（单个单词会被拆分）
 * 2. overflow-wrap（原名 word-wrap）
 *    2.1 break-word：在 word-break: break-all 的基础上，当一个单词一整行都显示不下会拆分单词换行
 */

// datalist：datalist 标签 id 与 input 的 list 属性对应，显示预选项

// 元素的 padding-top , padding-bottom , margin-top , margin-bottom 等按百分比设定时，依据的是父容器的宽度

/** line-height
 * 1. 设置为 normal：一般为 1.2
 * 2. 设置为百分比：行高为 font-size * 百分比，比如 16px * 120% = 19.2px
 * 3. 设置为数字：行高为 font-size * 数字，比如 16px * 1.2 = 19.2px
 * 4. 上述两者的区别在于继承：若父元素定义为百分比，那么子元素继承的是父元素的乘算结果即 19.2px；若父元素定义为数字，则子元素继承的是父元素定义的数字即 1.2
 */

// font-weight: normal 相当于 400

// opacity: 0 兼容写法：filter: alpha(opacity=0);

/** html5 新增表单元素
 * 1. datalist
 * 2. keygen
 * 3. output
 */

/** css3 部分伪类选择器
 * 1. :root：根节点，也就是 html 标签
 * 2. :target：当前活动锚点
 * 3. :empty：没有子元素（包括文本）的标签
 */

// 4 位的十六进制中前 3 位表示 rgb 三颜色，最后一位表示透明度（0~f）。因此 rgb: #f00f 表示 rgba(255, 0, 0, 1)

// cubic-bezier(x1,y1,x2,y2)：四个点分别为 (0,0) 、(x1,y1) 、(x2,y2) 、(1,1)

// embed：插入多媒体，通过 src 指定媒体文件

// 可以继承的属性很少，只有颜色，文字，字体间距行高对齐方式，和列表的样式可以继承。 所有元素可继承：visibility 和 cursor。 内联元素可继承：letter-spacing、word-spacing、white-space、line-height、color、font、font-family、font-size、font-style、font-variant、font-weight、text-decoration、text-transform、direction。 终端块状元素可继承：text-indent 和 text-align。列表元素可继承：list-style、list-style-type、list-style-position、list-style-image

/** 响应式图片
 * 1. width: 100%; max-width: 200px
 * 2. 为不同尺寸图片设计不同大小的图片
 * 3. img 标签 srcset 属性会根据不同设备像素比使用不同图片：srcset="img2xUrl 2x, img3xUrl 3x"
 */

/** H5，CSS3 新特性
 * 1. 语义化标签：SEO，结构清晰，易于维护。如 header,nav,main,article,section(一个部分/区段),aside(侧边栏),footer,small(细则，声明，版权),hgroup(标题组)。。。
 * 2. data-，dataset：<p id="p" data-text="hello"></p>，document.getElementById('p').dataset.text
 * 3. 新 input type：email，url，【number，range（min，max，step）】，search
 * 4. audio 支持 ogg,mp3,wav；video 支持 mp4,webm,ogg
 * 5. input 标签 pattern 属性写入正则表达式来验证文本
 */

/** H5新增标签：
 * article: 标签定义外部的内容
 * aside: 标签定义 article 以外的内容
 * audio: h5 新增音频标签。没有高宽属性
 * canvas: h5 新增画布标签
 * command: 定义命令按钮（未测试）
 * datalist：标签定义选项列表
 * datalist 及其选项不会被想显示出来，它仅仅是合法的输入值列表
 * details：标签用于描述文档或文档某个部分的细节
 * figure：标签用于对元素进行组合
 * figcaption：定义 figure 元素的标题
 * footer：定义 section 或 document 的页脚
 * header：定义 section 或 document 的页眉
 * hgroup：用于对网页或区段（section）的标题进行组合
 * keygen: 标签规定用于表单的密钥对生成器字段
 * mark：标签定义带有记号的文本
 * meter：通过 min="0" max="20" 的方式定义度量衡。仅用于已知最大和最小值的度量
 * nav：定义 document 或 section 或 article 的导航
 * output：定义不同的输出类型，比如脚本
 * progress：定义任何类型的任务的进度
 * rp: 定义若浏览器不支持 ruby 元素显示的内容
 * rt：定义 ruby 注释的解释
 * ruby：定义 ruby 注释
 * section：标签定义文档中的节、区段。比如章节、页眉、页脚或文档中的其他部分
 * source: audio 和 video 的属性之一。为 audio 和 video 定义媒介源
 * summary:为 details 定义标题
 * time: 定义日期或时间
 * video：h5 新增视频标签。具有高宽属性
 */
```

```css
/* 动画
  @keyframes
  animation：
      1. animation-name
      2. animation-duration
      3. animation-timing-function：linear ，ease-(in/out/in-out) ，cubic-bezier()
      4. animation-delay
      5. animation-iteration-count：n ，infinite
      6. animation-direction：normal ，alternate
  animation-play-state: paused ，running
  animation-fill-mode:
      1. none
      2. forwards：动画结束后保持最后的状态
      3. backwards：在 animation-delay 时就应用动画初始状态
      4. both
*/

#box {
  width: 100px;
  height: 100px;
  background-color: red;
  animation: run 1s linear 0s 3 alternate;
  animation-fill-mode: forwards;
}
@keyframes run {
  from {
    margin-left: 0;
  }
  to {
    margin-left: 300px;
  }
}

/* 过渡
  transition：
      1. transition-property
      2. transition-duration
      3. transition-timing-function：linear ，ease-(in/out/in-out) ，cubic-bezier()
      4. transition-delay
*/

#box {
  transition: height 1s ease;
}
#box:hover {
  height: 200px;
}

/* flex
  两大概念：容器（设置 flex 的元素），项目（容器的子元素）
  容器：
    存在两根轴：主轴和交叉轴，主轴默认水平方向。项目沿主轴方向在轴线上排列
    六大属性：
      1. flex-direction：主轴方向。row(-reverse，反向) ，column(-reverse)
      2. flex-wrap：项目一条轴线排不下时如何换行。nowrap ，wrap(-reserve)
      3. flex-flow：flex-direction + flex-wrap
      4. justify-content：项目在主轴对齐方式。flex-(start/end) ，center ，space-(between/around(左右间隔相等))
      5. align-items：项目在交叉轴对齐方式。flex-(start/end) ，center ，baseline(项目第一行子对齐) ，stretch(项目未设置高度或为 auto 则占满容器高度)
      6. align-content：多根主轴情况下在交叉轴对齐方式。flex-(start/end) ，center ，space-(between/around) ，stretch
  项目：
    六大属性：
      1. order：一个排序用的数值，数值越小排行越前，默认 0
      2. flex-grow：项目放大比例，默认 0。项目均为 1 即平分剩余空间
      3. flex-shrink：项目缩写比例，默认 1。项目均为 1 即空间不足时等比例缩小，0 表示不缩小
      4. flex-basis：项目分配剩余空间前占据主轴多少空间。默认 auto ，可设置为 px
      5. flex：flex-grow + flex-shrink + flex-basis
      6. align-self：单个项目与其他项目不同的对齐方式（覆盖 align-items）：auto ，flex-(start/end) ，center ，baseline ，stretch
*/

#container {
  margin: 20px 0;
  width: 900px;
  height: 300px;
  background-color: #eee;
  display: flex;
  justify-content: space-between;
  align-items: center;
}
.item {
  flex: 0 0 200px;
  height: 200px;
  border: 1px solid #000;
}

/* 垂直居中
  1. 子绝父相，子 top50% ，translateY(-50%)
  2. 子绝父相，子 top bottom 任意相同数值，margin: auto 0
  3. 父不设置高度，padding: 10px 0
  4. 父 flex ，子 margin: auto 0
  5. 父 flex ，align-items: center
  6. 父 flex ，flex-direction: column ，justify-content: center
  7. 文本垂直居中：line-height: height
  8. 父 table ，子 table-cell ，vertical-align: middle
  9. vertical-align：
    9.1 适用范围：inline / inline-block 元素可使用，比如 span ，img ，input ，button ，td 或者手动设置了 display 的元素
    9.2 值：top ，bottom ，middle ，baseline ...
*/

#fa {
  width: 300px;
  height: 300px;
  background-color: #eee;
  position: absolute;
  margin-top: 20px;
}
#son {
  width: 100px;
  height: 100px;
  background-color: #fff;
  position: absolute;
  top: 0;
}

/* position
  absolute：相对 static 定位外的第一个父元素定位
  fixed
  relative：相对其正常位置定位
  static：无定位，默认
  sticky：粘性定位，依赖于用户的滚动，滚动未超出可视区时，就类似于 relative ;滚动出可视区切换为 fixed。必须设置一个特定阈值（top，left...）使粘性定位（fixed 时）生效
*/

body {
  height: 1000px;
}
#position {
  width: 50px;
  height: 50px;
  background-color: rebeccapurple;
  position: sticky;
  top: 0;
}

/* 正方形
  1. 父设好宽度；子：height: 0; padding-bottom: 100%;
  2. position: absolute; padding: 20% 20% 0 0;
  3. vw，vh，vmin，vmax
*/

#zc {
  width: 200px;
}
#z {
  /*height: 0;*/
  /*padding-bottom: 100%;*/
  background-color: rebeccapurple;
  position: absolute;
  padding: 20% 20% 0 0;
}

/* table
  cellspacing：单元格之间的间隔
  cellpadding：单元格内边距
  border-collapse：设置表格边框分隔（separate）还是合并（collapse）
*/

table {
  border-collapse: collapse;
}
table, th, td {
  border: 1px solid #000;
}
th, td {
  width: 200px;
  height: 60px;
}

/* 文本溢出 */
div {
  overflow: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
}

/* box-shadow: 水平阴影位置 垂直阴影位置 模糊距离 阴影大小 颜色 inset（内侧） */
#shadow {
  margin: 100px;
  width: 100px;
  height: 100px;
  box-shadow: 1px 1px 10px 5px #666;
}

/* background-position
  1. 单值：center , top , bottom , right , left 。另一个维度默认为 50%
  2. 双值：% 或 px ，表示往右 ， 往下偏移
  3. 双值：center , top , bottom , right , left
*/
/* background-repeat：repeat , no-repeat , repeat-x , repeat-y
  1. 单值
  2. 双值
*/
/* background-size：contain（变形）, cover , px , %（px ，% 可双值） */
/* background-attachment：fixed ，scroll */
#background {
  margin: 100px 0 0 100px;
  width: 400px;
  height: 400px;
  border: 10px solid #000;
  background:  url("../others/yuanxing.png") 50% 20px no-repeat ;
}

/* 线性渐变：linear-gradient */
/* 径向渐变：radial-gradient 不能指定方向，默认为由内到外 */
#linear {
  width: 300px;
  height: 60px;
  background: radial-gradient(rgba(34, 25, 85, .3), rgba(134, 255, 25, .6));
}

/* transform
  1. rotate(X/Y/Z)(xxxdeg)
  2. scale(X/Y/Z)(x,y,z)
  3. translate(X/Y/Z)
*/
/* transform-origin: 旋转基点 ，对应 x , y , z 三条轴（px ，% ，left） */
```
